// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_l-E-oNmRAMR5KiZfT-_e2mNTfolkg3g',
    appId: '1:394699809635:web:2bcc880bdebe87f53ba956',
    messagingSenderId: '394699809635',
    projectId: 'trackle-48049',
    authDomain: 'trackle-48049.firebaseapp.com',
    storageBucket: 'trackle-48049.firebasestorage.app',
    measurementId: 'G-7M4V1X7RWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPfb-E3sJegTP_OCMmdrr1TmsUPzwanR4',
    appId: '1:394699809635:android:67a7a1a11dbe299e3ba956',
    messagingSenderId: '394699809635',
    projectId: 'trackle-48049',
    storageBucket: 'trackle-48049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHwWMky9blj8lpnaiZq2RIeTUNTPPSQW4',
    appId: '1:394699809635:ios:23eea2820b6af71f3ba956',
    messagingSenderId: '394699809635',
    projectId: 'trackle-48049',
    storageBucket: 'trackle-48049.firebasestorage.app',
    iosBundleId: 'com.example.trackle',
  );
}
